version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=dbunlockr
      - DB_USER=unlockr_admin
      - DB_PASSWORD=LiLEXXhP2727@

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=dbunlockr
      - POSTGRES_USER=unlockr_admin
      - POSTGRES_PASSWORD=LiLEXXhP2727@
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres_data:
